### ISSUE TITLE
Capture does not work at all in recent Chrome

### ISSUE THREAD

**Issue by rillig** [tlrobinson/element-capture#7]
As noted in one of the reviews, in recent versions of Chrome, the extension needs the `activeTab` permission to work. I just added it in the `manifest.json`, and now capturing works again.

This helps against the several one-star ratings saying “the extension doesn’t work at all”.

**Comment by niftylettuce** [comment]
:+1: @tlrobinson plz fix!

**Comment by tlrobinson** [comment]
Merged, thanks.

**Comment by rillig** [comment]
I informed the one-star reviewers in the Chrome Web Store, so maybe they will change their mind now that it works again. :)
